name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov
          extensions: mbstring, intl, dom, xml
          tools: composer
      - run: composer install --no-interaction --prefer-dist
      - run: make lint
      - run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          files: coverage.xml
          disable_search: true
          fail_ci_if_error: true
